<?xml version="1.0"?>

<robot name="imu" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="height1" value="0.2" />
  <xacro:property name="width" value="0.2" />

 <!-- Used for fixing imu to camera 'camera_link' -->
  <link name="camera_link"/>

  <joint name="fixed" type="fixed">
    <parent link="camera_link"/>
    <child link="imu"/>
  </joint>

 <!-- Base Link -->
  <link name="imu">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>


  <material name="orange">
    <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
  </material>
 <gazebo reference="imu">
    <material>Gazebo/Orange</material>
  </gazebo>

  <gazebo>
    <plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
      <alwaysOn>true</alwaysOn>
      <bodyName>imu</bodyName>
      <topicName>imu_gazebo</topicName>
      <serviceName>imu_service</serviceName>
      <gaussianNoise>0.0</gaussianNoise>
      <updateRate>20.0</updateRate>
    </plugin>
  </gazebo>

</robot>
